### ISSUE TITLE
h5repack error

### ISSUE THREAD

**Issue by adithi-varadarajan** [PacificBiosciences/pbalign#11]
Hi,

I was running pbalign with input.fofn files directing towards bax.h5 files from PacBio using this command:

    pbalign --nproc 2 --forQuiver input.fofn sprai_run_successful/result_20150518_135211/CA/9-terminator/asm_CA_01_20150518_231322.scf.fasta reads_mappedto_scaffolds_sprai.cmp.h5

When I first time I was running this command, it run through successfully. But when the same command was run second time with the same input files, it gave me this error:
```
[ERROR] RepackService returned a non-zero exit status. HDF5-DIAG: Error detected in HDF5 (1.8.8) thread 140652913485568:
  #000: ../../../src/H5D.c line 170 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: ../../../src/H5Dint.c line 431 in H5D_create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: ../../../src/H5L.c line 1639 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: ../../../src/H5L.c line 1883 in H5L_create_real(): can't insert link
    major: Symbol table
    minor: Unable to insert object
  #004: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: ../../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: ../../../src/H5L.c line 1686 in H5L_link_cb(): unable to create object
    major: Object header
    minor: Unable to initialize object
  #007: ../../../src/H5O.c line 3013 in H5O_obj_create(): unable to open object
    major: Object header
    minor: Can't open object
  #008: ../../../src/H5Doh.c line 295 in H5O_dset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #009: ../../../src/H5Dint.c line 1035 in H5D_create(): unable to construct layout information
    major: Dataset
    minor: Unable to initialize object
  #010: ../../../src/H5Dchunk.c line 432 in H5D_chunk_construct(): chunk size must be <= maximum dimension size for fixed-sized dimensions
    major: Dataset
    minor: Unable to initialize object
h5repack error: </home/bioinf/bioinf_data/30_vaad/thiodyction_example/sprai_pbalign_quiver_prokka/reads_mappedto_scaffolds_sprai.cmp.h5>: Could not copy data to: /home/bioinf/bioinf_data/30_vaad/thiodyction_example/sprai_pbalign_quiver_prokka/reads_mappedto_scaffolds_sprai.cmp.h5.TMP.
```
Does anybody has an idea why it complains that it cannot write data to the respective diretory. I tried my best to find a solution but nothing helped.
Any reply would be highly appreciated.

Thanks in advance

**Comment by ylipacbio** [comment]
Would you please check whether the file reads_mappedto_scaffolds_sorai.cmp.h5.TMP already exists or the directory (sprai_pbalign_quiver_prokka) has write permission and enough space and disk quota?

**Comment by adithi-varadarajan** [comment]
Thanks for your reply. 
Yes the file already exists in the folder but they were created by pbalign itself during running. So, I dont get the point why it terminates with that error message.

**Comment by ylipacbio** [comment]
The point is that if you ran this command successfully for the first time, but failed for the second time, this error may be caused by not able to create or overwrite a file e.g., not having the write/overwrite permission, exceeding the disk quota, not having enough space etc.

Would you please also check that reads_mappedto_scaffolds_sorai.cmp.h5 is not corrupted. You may use 

    h5ls -r reads_mappedto_scaffolds_sorai.cmp.h5 

h5repack is the very last step in pablign with --forQuiver, So if reads_mappedto_scaffolds_sorai.cmp.h5 is not corrupted, you may use it as pbalign output directly.

**Comment by adithi-varadarajan** [comment]
Thanks again. 
I checked already for all the possibilities that you mentioned. But none of them were the case. Everything seems all right. Anyways as you suggested, I did check with the 'h5ls' and it seemed to be okay. Processed it further for Quiver and yes it worked fine.

Thanks for the help.
