### ISSUE TITLE
pbalign v 0.2.0_imput not clear to me

### ISSUE THREAD

**Issue by kemya** [PacificBiosciences/pbalign#13]
On the page  the legal input format files listed are:
```
    FASTA : .fa or .fasta
    PacBio BASE HDF5 : .bas.h5 or .bax.h5
    PacBio PULSE HDF5 : .pls.h5 or .plx.h5
    PacBio CCS HDF5 : .ccs.h5
    File of file names : .fofn
```
then on the "divide and conquer" approach (https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign) I found:

      First, create a fofn (File of File Name) file for each SMRTCell. There are three bax.h5 files           generated for each SMRTCell. You may save (paths to) the three bax.h5 files in a fofn file.

Unluckily when I try to run 

    pbalign --nproc 8  --forQuiver --verbose $INPUT.fofn $REFER.fasta $OUT.cmp.h5

I get this error:
```python
Traceback (most recent call last):
  File "/SMRT/current/analysis/bin/pbalign", line 8, in <module>
    load_entry_point('pbalign==0.2.0', 'console_scripts', 'pbalign')()
  File "//SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 289, in main
    return pbobj.start()
  File "//SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 105, in start
    return self.run()
  File "/SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 228, in run
    self._makeSane(self.args, self.fileNames)
  File "/SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 143, in _makeSane
    raise ValueError(errMsg)
ValueError: Neither the input file is in bas/pls/ccs.h5 format, nor --pulseFile is specified, , while --forQuiver is true.
```
And the error message is not lying.. my input file is a .fofn containing three .bax.h5 files

On the help page of pbalign I have found:
```
--forQuiver           The output cmp.h5 file which will be sorted, loaded
                        with pulse information, and repacked, so that it 
                        can be consumed by quiver directly. This requires
                        the input file to be in PacBio bas/pls.h5 format.
                        Default value is False.
```
Now I'm truly confused I thought my input was fine, help please!

Kem

**Comment by ylipacbio** [comment]
Would you please check your input.fofn

cat input.fofn |xargs h5ls -r 

(pbalign --forQuiver) requires bax.h5 as input, which contains all the QV values.

**Comment by ylipacbio** [comment]
Please reopen this issue if you haven't sorted this out.

**Comment by shameem356** [comment]
Hello @ylipacbio ,

I am also getting the same error while running pbaligner.

**Here is my command** 

pbalign --forQuiver input.fofn references_folder aligned_reads.chunk001.cmp.h5 --verbose --nproc 12 --seed=1 --tmpDir=mrtanalysis/tmpdir --minAccuracy=0.75 --minLength=50 --concordant --algorithmOptions=-useQuality --hitPolicy=randombest 

**input.fofn file content**
Analysis_Results/m150114_170805_42226_c100663992550000001823134212201420_s1_X0.1.bax.5
Analysis_Results/m150114_170805_42226_c100663992550000001823134212201420_s1_X0.2.bax.5
Analysis_Results/m150114_170805_42226_c100663992550000001823134212201420_s1_X0.3.bax.5

Please can you suggest me how to trouble shoot this error.
