### ISSUE TITLE
cannot loadChemistry.py with older sequencing cells (2013)

### ISSUE THREAD

**Issue by gleveq1** [PacificBiosciences/pbalign#18]
For cells coming from 2013;  contained either in just one .bas.h5 file or  one .bas.h5 plus 3 .bax.h5,  I cannot get loadChemistry.py to work with smrtanalysis_2.3.0.140936.p5.

The metadata.xml files are where they are supposed to be and --forQuiver is used for pbalign/blasr.

Here is the error for loadChemistry.py:

[INFO] ForQuiverService: LoadChemistry.
2015-12-22 10:59:10,043 [INFO] LoadChemistryService: Load pulses using loadChemistry.py.
2015-12-22 10:59:10,043 [DEBUG] LoadChemistryService: Call "loadChemistry.py /lb/project/mugqic/projects/Gary/Bekal/KID-111939_replacement/filtering/input.fofn /lb/project/mugqic/projects/Gary/Bekal/KID-111939_replacement/30X/merSize14/polishing1/data/aligned_reads.cmp.h5 "
2015-12-22 10:59:15,625 [ERROR] LoadChemistryService returned a non-zero exit status. Traceback (most recent call last):
  File "/cvmfs/soft.mugqic/CentOS6/software/smrtanalysis/smrtanalysis_2.3.0.140936.p5/analysis/bin/loadChemistry.py", line 8, in <module>
    load_entry_point('pbalign==0.2.0', 'console_scripts', 'loadChemistry.py')()
  File "/cvmfs/soft.mugqic/CentOS6/software/smrtanalysis/smrtanalysis_2.3.0.140936.p5/redist/python2.7/lib/python2.7/site-packages/pbalign/tools/loadChemistry.py", line 72, in main
    chemTriple = bas.chemistryBarcodeTriple
  File "/cvmfs/soft.mugqic/CentOS6/software/smrtanalysis/smrtanalysis_2.3.0.140936.p5/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 860, in chemistryBarcodeTriple
    return self._parts[0].chemistryBarcodeTriple
  File "/cvmfs/soft.mugqic/CentOS6/software/smrtanalysis/smrtanalysis_2.3.0.140936.p5/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 624, in chemistryBarcodeTriple
    raise ChemistryLookupError, "Could not find chemistry barcodes in file or companion metadata.xml"

I tried:  h5ls -r aligned_reads.cmp.h5     on my pbalign/blasr output aligned_reads.cmp.h5 .

/                        Group
/AlnGroup                Group
/AlnGroup/ID             Dataset {12/Inf}
/AlnGroup/Path           Dataset {12/Inf}
/AlnInfo                 Group
/AlnInfo/AlnIndex        Dataset {143412/Inf, 22/Inf}
/FileLog                 Group
/FileLog/CommandLine     Dataset {2/Inf}
/FileLog/ID              Dataset {2/Inf}
/FileLog/Log             Dataset {2/Inf}
/FileLog/Program         Dataset {2/Inf}
/FileLog/Timestamp       Dataset {2/Inf}
/FileLog/Version         Dataset {2/Inf}
/MovieInfo               Group
/MovieInfo/FrameRate     Dataset {1/Inf}
/MovieInfo/ID            Dataset {1/Inf}
/MovieInfo/Name          Dataset {1/Inf}
/RefGroup                Group
/RefGroup/ID             Dataset {12/Inf}
/RefGroup/OffsetTable    Dataset {12/Inf, 3/Inf}
/RefGroup/Path           Dataset {12/Inf}
/RefGroup/RefInfoID      Dataset {12/Inf}
/RefInfo                 Group
/RefInfo/FullName        Dataset {12/Inf}
/RefInfo/ID              Dataset {12/Inf}
/RefInfo/Length          Dataset {12/Inf}
/RefInfo/MD5             Dataset {12/Inf}
/ref000001               Group
/ref000001/rg1-0         Group
/ref000001/rg1-0/AlnArray Dataset {136107695/Inf}
.
.
.
My impression is that there is no Chemistry information (in MovieInfo/) loaded (because it does not exist??) and the "chemistryBarcodeTriple" search crashes.

Thanks for any insight!
GL

**Comment by ylipacbio** [comment]
It seems like metadata.xml is not found. The directory for saving bas.h5/bax.h5 files should look like the following:
```
moviename.metadata.xml
some other files which do not matter 
Analysis_Results/moviename.1.bax.h5
Analysis_Results/moviename.2.bax.h5
Analysis_Results/moviename.3.bax.h5
Analysis_Results/moviename.bas.h5
```

A correct output cmp.h5 file produced by ```pbalign fofn ref out.cmp.h5 --forQuiver``` should look like:
```
/                        Group
/AlnGroup                Group
/AlnGroup/ID             Dataset {1/Inf}
/AlnGroup/Path           Dataset {1/Inf}
/AlnInfo                 Group
/AlnInfo/AlnIndex        Dataset {112/Inf, 22/Inf}
/FileLog                 Group
/FileLog/CommandLine     Dataset {2/Inf}
/FileLog/ID              Dataset {2/Inf}
/FileLog/Log             Dataset {2/Inf}
/FileLog/Program         Dataset {2/Inf}
/FileLog/Timestamp       Dataset {2/Inf}
/FileLog/Version         Dataset {2/Inf}
/MovieInfo               Group
/MovieInfo/BindingKit    Dataset {1/Inf}  # important chemistry info
/MovieInfo/FrameRate     Dataset {1/Inf}
/MovieInfo/ID            Dataset {1/Inf}
/MovieInfo/Name          Dataset {1/Inf}
/MovieInfo/SequencingKit Dataset {1/Inf} # important chemistry info
/MovieInfo/SoftwareVersion Dataset {1/Inf}  # important chemistry info
/RefGroup                Group
/RefGroup/ID             Dataset {1/Inf}
/RefGroup/OffsetTable    Dataset {1/Inf, 3/Inf}
/RefGroup/Path           Dataset {1/Inf}
/RefGroup/RefInfoID      Dataset {1/Inf}
/RefInfo                 Group
/RefInfo/FullName        Dataset {1/Inf}
/RefInfo/ID              Dataset {1/Inf}
/RefInfo/Length          Dataset {1/Inf}
/RefInfo/MD5             Dataset {1/Inf}
/ref000001               Group
/ref000001/rg1-0         Group
/ref000001/rg1-0/AlnArray Dataset {61514/Inf}
/ref000001/rg1-0/DeletionQV Dataset {61514/Inf} # important QV info
/ref000001/rg1-0/DeletionTag Dataset {61514/Inf} # important QV info
/ref000001/rg1-0/InsertionQV Dataset {61514/Inf} # important QV info
/ref000001/rg1-0/MergeQV Dataset {61514/Inf} # important QV info
/ref000001/rg1-0/SubstitutionQV Dataset {61514/Inf} # important QV info
```

**Comment by gleveq1** [comment]
As mentioned the metadata.xml is where it is supposed to be along with the other files you point out.
Is there a place where I can upload the files for troubleshooting?
Thank you.

**Comment by ylipacbio** [comment]
@pb-jlandolin would you please help with uploading files for troubleshooting? Thanks

**Comment by pb-jlandolin** [comment]
We only have ftp for existing customers, however, @gleveq1, if you put it on dropbox or google docs, we will be happy to download it.

**Comment by pb-jlandolin** [comment]
What University/institution are you from?  I can send you an ftp if you have an instrument.

**Comment by gleveq1** [comment]
Hi,

We have an RSII instrument here at the McGill University and Genome Quebec
Innovation Center in Montreal , Quebec.

Sonny Mark is our FAS.

Thanks
GL

**Comment by ylipacbio** [comment]
any updates on this thread? @pb-jlandolin

**Comment by esolares** [comment]
Hi, was this ever resolved?

**Comment by gleveq1** [comment]
No this was never resolved;  we have moved on.
