### ISSUE TITLE
Pbalign --ForQuiver prepared files failing to process through Quiver

### ISSUE THREAD

**Issue by djwilki** [PacificBiosciences/pbalign#19]
Hello,

I am trying to run Quiver with the outputs of pbalign --forQuiver, but whenever I attempt to run Quiver, it outputs empty files and the quiverResult.vc.err file contains the following:

[INFO] h5py version: 2.2.0
[INFO] hdf5 version: 1.8.12
[INFO] ConsensusCore version: 0.7.6
[INFO] Starting.
[INFO] Peeking at CmpH5 file /home/lab/Desktop/clusteringConsensus-master/A01/hivalign.cmp.h5
[INFO] Input CmpH5 data: numAlnHits=81274
[INFO] Loading reference

Quiver isn't throwing any errors in the command window either.

Our cmp.h5 file preparation was as follows:

pbalign --forQuiver DATA.baxh5.fofn HIVemory.fasta hivalign.cmp.h5

with the fofn file containing our relevant bax.h5 files.

I'm just a little stumped at this point, as the --ForQuiver isn't seeming to be sufficient.

Thank you,
DJWILKI

**Comment by ylipacbio** [comment]
May I ask you a few questions:
(1) did you see any alignments in output cmp.h5 file produced by
 `pbalign DATA.baxh5.fofn HIVemory.fasta no_quiver_hivalign.cmp.h5`  (no use --forQuiver) ?
(2) Would you please try 
`pbalign --verbose DATA.baxh5.fofn HIVemory.fasta hivalign.cmp.h5 --forQuiver --keepTmpFiles`
or 
`pbalign -v -v DATA.baxh5.fofn HIVemory.fasta hivalign.cmp.h5 --forQuiver --keepTmpFiles`
depending on pbalign version and post the log please?
(3) How many bax.h5 files in the input DATA.baxh5.fofn? To deal with large number of bax.h5 files, please look at [this tutorial](https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign)
