### ISSUE TITLE
Cannot create cmp.h5 file: ERROR, could not read pulse metrics for SMRTSequence

### ISSUE THREAD

**Issue by marcelauliano** [PacificBiosciences/pbalign#20]
Hey guys! Sorry, I'm writing here because I haven't found any way through this online.

I have an assembly done with DBG2OCL and want to quiver it. For that, I have to create the cmp.h5 file. I have 10 SMTRCells, so I've created fofn files for each of them (with the path to the 3 bax.h5 files for each) and I'm trying to run pbalign. 

I get the error message:
```
2016-01-22 03:54:47,272 [ERROR] BlasrService returned a non-zero exit status. [INFO] 2016-01-22T03:12:17 [blasr] started.
ERROR, could not read quality metrics for FASTQ Sequence m151007_131251_42182_c100905882550000001823201404301681_s1_p0/6034
2016-01-22 04:54:05,834 [ERROR] BlasrService returned a non-zero exit status. [INFO] 2016-01-22T03:54:47 [blasr] started.
ERROR, could not read pulse metrics for SMRTSequence m151009_210944_42182_c100906002550000001823201404301691_s1_p0/14953
```
My questions is: do I also need the bas.h5 file in the same folder where the bax.h5 are?

Just to mention: I needed to install pbalign and its dependencies independently because the cluster where I work don't allow me to install the entire smartanalysis software. But my installation, inside the virtual machine, has not encountered any errors.

Thank you so much!

**Comment by ylipacbio** [comment]
I am wondering which version of blasr are you using. Would you please try the [latest version](https://github.com/PacificBiosciences/blasr).

Blasr used to require to read all QVs and is no longer required to do so if a certain QV does not exist.

**Comment by linz-li** [comment]
marcelauliano ,I have a same question with you . Have you solve it? 
I have check the cell like your m151009_210944_42182_c100906002550000001823201404301691_s1_p0/14953
the 'good' news is this reads is not exist, and the next reads 14954 have two copy ,  So I think this is the problem.
But the question is how to edit the bax.h5 file ?

**Comment by ylipacbio** [comment]
In order to change an existing bax.h5 file, the only way that I know might be manually editing it using h5py through python.

A possible alternative way to go around this issue is to add ```-holeNumber  0-14952,149545-170000``` to blasr cmd in order to skip zmw 14953.

e.g.

```blasr input.fofn ref.fasta -holeNumbers 0-14952,149545-170000 ```

**Comment by ylipacbio** [comment]
Please reopen this issue if you still have questions.

**Comment by guleiathms** [comment]
I also met the same error, and found this post.

I met this error when I run the smrtanalysis_2.3.0.140936 with patch 5 for 28 movies (28 ...p0.1.bax.h5, p0.2.bax.h5, p0.3.bax.h5), and got 

"2016-06-05 01:19:23,470 [ERROR] BlasrService returned a non-zero exit status. [INFO] 2016-06-04T16:09:37 [blasr] started.
ERROR, could not read pulse metrics for SMRTSequence m140929_122654_42139_c100719602550000001823155305141594_s1_p0/92444"
in the align.log.

Then I run the same pipeline for that potential problematic moive (m140929_122654_42139_c100719602550000001823155305141594_s1_p0), but no error reported, with exit code 0:

"Task 1 completed at Fri Jun  3 20:51:02 EDT 2016
Alignment Complete
Task 2 completed at Fri Jun  3 20:51:02 EDT 2016
[INFO] 2016-06-03T20:51:05 [loadPulses] started.
loading 199520 alignments for movie 1
loading 199520 alignments for movie 1
loading 199520 alignments for movie 1
loading 163226 alignments for movie 2
loading 163226 alignments for movie 2
loading 163226 alignments for movie 2
[INFO] 2016-06-03T21:52:34 [loadPulses] ended.
Task 3 completed at Fri Jun  3 21:52:34 EDT 2016
LoadPulses Complete
Task 4 completed at Fri Jun  3 21:52:34 EDT 2016
Finished on Sat Jun  4 01:52:34 UTC 2016
Task align with nproc 8 with exit code 0.
"

So what's going on when I run the pipeline with 28 movies together?

**Comment by pb-cdunn** [comment]
@guleiathms also filed as #34.

**Comment by marcelauliano** [comment]
Hey guys,
Just to let you know that in my case it was a version problem. At the beginning, I did not have permission to install the hole smartanalysis package in the computer cluster where I work. So I was running blasr, pbalign and etc all separetly in different computers. Once I could run all together, the problem was gone.

So, please mind if the version of blasr and/or pbalign you guys are using generates all the output nedded for quiver or other downstream analysis!

Good luck!

**Comment by ylipacbio** [comment]
Hi Marcela, thank you for your feedback.

The issue that guleiathms observed does seem to be related with blasr version. There was a bug in blasr_libcpp which caused blasr to raise this error when any (non-mandatory) QV is missing and this bug should have been fixed.

Would you please check that blasr used in two pipelines identical?

In addition, the following command helps to duplicate this error quickly:
```
blasr m140929_122654_42139_c100719602550000001823155305141594_s1_p0.fofn ref.fasta -holeNumbers 92000-100000 
```
