### ISSUE TITLE
[ERROR] BlasrService returned a non-zero exit status. 

### ISSUE THREAD

**Issue by yjx1217** [PacificBiosciences/pbalign#21]
Hello,

I encountered this error when running command: "pbalign --forQuiver --tmpDir /tmp input.bas.h5 assembly.fa test.cmp.h5" . This is the only error message that I got. Could you help me to figure out what might cause this error? Thanks!

The blasr that I am using is v3.0.1.

**Comment by yjx1217** [comment]
OK, I think I might have found the cause. It seems that the blasr installed on our server doesn't work properly for some reason. After replacing it with a brand new blasr installation, the problem seems solved.

**Comment by pb-cdunn** [comment]
Great!

We should get the git checksum added to the version number.
