### ISSUE TITLE
 [ERROR] BlasrService returned a non-zero exit status

### ISSUE THREAD

**Issue by haryypeng** [PacificBiosciences/pbalign#27]
`2016-04-19 09:08:40,663 [INFO] pbalign version: 0.2.0.138342`
`2016-04-19 09:08:40,663 [DEBUG] Original arguments: ['-vv', './split_map/input1.fofn', '/exporthome/ptian/organism/software/smrtanalysis/organism/reference/organism_ctg', './split_map/aligned1.cmp.h5', '--seed=1', '--minAccuracy=0.75', '--minLength=1000', '--algorithmOptions=-useQuality', '--algorithmOptions= -minMatch 12 -bestn 10 -minPctIdentity 70.0 -sa /exporthome/ptian/organism/software/smrtanalysis/organism/reference/organism_ctg/sequence/organism_ctg.fasta.sa', '--hitPolicy=randombest', '--tmpDir=/exporthome/ptian/organism/software/smrtanalysis/tmpdir', '--nproc=63', '--regionTable=./split_map/filtered_regions1.fofn']`
`2016-04-19 09:08:42,905 [DEBUG] Parsed arguments considering configFile and algorithmOptions: Namespace(algorithm='blasr', algorithmOptions='-useQuality  -minPctIdentity 70.0', byread=False, concordant=False, configFile=None, debug=False, filterAdapterOnly=False, forQuiver=False, hitPolicy='randombest', inputFileName='./split_map/input1.fofn', keepTmpFiles=False, maxDivergence=30, maxHits=10, metrics='DeletionQV,DeletionTag,InsertionQV,MergeQV,SubstitutionQV', minAccuracy=0.75, minAnchorSize=12, minLength=1000, noSplitSubreads=False, nproc=63, outputFileName='./split_map/aligned1.cmp.h5', profile=False, pulseFile=None, readType='standard', referencePath='/exporthome/ptian/organism/software/smrtanalysis/organism/reference/organism_ctg', regionTable='./split_map/filtered_regions1.fofn', scoreCutoff=None, scoreFunction='alignerscore', seed=1, tmpDir='/exporthome/ptian/organism/software/smrtanalysis/tmpdir', useccs=None, verbosity=2)`
`2016-04-19 09:08:42,917 [INFO] BlasrService: Align reads to references using blasr.`
`2016-04-19 09:08:42,918 [DEBUG] BlasrService: Call "blasr /exporthome/ptian/organism/software/smrtanalysis/organism/organism_ana/split_map/input1.fofn /exporthome/ptian/organism/software/smrtanalysis/organism/reference/organism_ctg/sequence/organism_ctg.fasta -sam -out /exporthome/ptian/organism/software/smrtanalysis/tmpdir/tmpv_kB4w/uLkopH.sam  -sa /exporthome/ptian/organism/software/smrtanalysis/organism/reference/organism_ctg/sequence/organism_ctg.fasta.sa  -regionTable /exporthome/ptian/organism/software/smrtanalysis/organism/organism_ana/split_map/filtered_regions1.fofn  -bestn 10 -minMatch 12  -nproc 63  -minSubreadLength 1000 -minReadLength 1000  -randomSeed 1  -placeRepeatsRandomly  -useQuality  -minPctIdentity 70.0 "
2016-04-19 10:09:57,420 [ERROR] BlasrService returned a non-zero exit status.`

The mem of my Linux CentOs 6.5 is 380G, which is sufficient for use. What's the problem it is. Can any one please tell me.

**Comment by haryypeng** [comment]
@nlhepler

**Comment by ylipacbio** [comment]
Would you please try the following command to just align the first 10000 zmws and post the error message?  Thanks

```blasr /exporthome/ptian/organism/software/smrtanalysis/organism/organism_ana/split_map/input1.fofn /exporthome/ptian/organism/software/smrtanalysis/organism/reference/organism_ctg/sequence/organism_ctg.fasta -sam -out tmp.sam -sa /exporthome/ptian/organism/software/smrtanalysis/organism/reference/organism_ctg/sequence/organism_ctg.fasta.sa -regionTable /exporthome/ptian/organism/software/smrtanalysis/organism/organism_ana/split_map/filtered_regions1.fofn -bestn 10 -minMatch 12 -nproc 63 -minSubreadLength 1000 -minReadLength 1000 -randomSeed 1 -placeRepeatsRandomly -useQuality -minPctIdentity 70.0 -holeNumbers 1-10000 ```
