### ISSUE TITLE
Is it possible to resume a loadPulses run?

### ISSUE THREAD

**Issue by eltonjrv** [PacificBiosciences/pbalign#31]
Hello PacBio folks,

My loadPulses run stopped because it reached the walltime limit I had added in my job script.
My *cmp.h5 file has increased more than 100Gb during the loadPulses run.
I wonder whether I can keep the same loadPulses command I am using to re-run it on this new incomplete increased cmp.h file.
I could not find any loadPulses options to resume an aborted execution.
Please don't tell I'll have to run pbalign again. ;-(

Thanks in advance for your always good support! ;-)
Best,
Elton

**Comment by ylipacbio** [comment]
Hi Elton,

If a cmp.h5 file exceeds more than 100G and loadPulses took a very long time, it usually indicates that you are using pbalign to process a large dataset while pbalign is designed to handle small to medium size files.  Please either use smrtanalysis or see [this](https://github.com/PacificBiosciences/pbalign/wiki/Tutorial:-How-to-divide-and-conquer-large-datasets-using-pbalign) page for how to handel large dataset in a divide and conquer way.

**Comment by ylipacbio** [comment]
Direct answer to your question:  sorry, loadPulses run could not be resumed.

**Comment by eltonjrv** [comment]
Thanks for getting back and shedding light, Yuan!

Ok, I will do the steps mentioned on the link you posted.
*There's only one question:*
Since I am supposed to run loadPulses on "n" small cmp.h5 files (because of
splitting input.fofn into "n" chunks and running pbalign "n" times), after
running "cmph5tools.py merge" and "cmph5tools.py sort" on the loadPulses
outputs, *will ipdSummary.py consider IPD values for the total coverage
from all my SMRTcells that were initially split?*

I am betting it will! But, just in case, I'd rather ask to the experts
first!

Thanks again for all your support,
Cheers,
Elton

2016-05-19 14:50 GMT-03:00 Yuan Li <notifications@github.com>:

> Direct answer to your question: sorry, loadPulses run could not be resumed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/PacificBiosciences/pbalign/issues/31#issuecomment-220401120>
>



-- 
Elton J. R. Vasconcelos
DVM, PhD

**Comment by ylipacbio** [comment]
Once ipd loaded to all cmp.h5 files and all cmp.h5 file merged  to a big file, ipdSummary should consider ipd values for the total coverage. 

One thing that worth trying is to add  ```--algorithmOptions=' -holeNumber 1-2000' ``` to all pbalign commands on the first try (so that only a subset of zmws from each movie are aligned) in order to see if the whole pipeline can finish successfully. That makes trouble shooting easier.

**Comment by eltonjrv** [comment]
Thanks Yuan!
Good idea about running the whole pipeline with a small sampling first!

I'll keep you posted if any other issue shows up!
Best,
Elton

2016-05-19 17:22 GMT-03:00 Yuan Li <notifications@github.com>:

> Once ipd loaded to all cmp.h5 files and all cmp.h5 file merged to a big
> file, ipdSummary should consider ipd values for the total coverage.
>
> One thing that worth trying is to add --algorithmOptions=' -holeNumbers
> 1-2000' to all pbalign commands on the first try (so that only a subset
> of zmws from each movie are aligned) in order to see if the whole pipeline
> can finish successfully. That makes trouble shooting easier.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/PacificBiosciences/pbalign/issues/31#issuecomment-220438199>
>



-- 
Elton J. R. Vasconcelos
DVM, PhD

**Comment by ylipacbio** [comment]
Please reopen this issue if needed.
