### ISSUE TITLE
Most recent update to blasr breaks pbalign 

### ISSUE THREAD

**Issue by peterdfields** [PacificBiosciences/pbalign#32]
with the removal of the -sam output option the basic pipeline presented in the examples will no longer work.

**Comment by vrainish-pacbio** [comment]
Hi Peter,

I'll fix the example. Thanks a lot for your comment.

**Comment by vrainish-pacbio** [comment]
Hi Peter, 

If you need an output file in SAM format , invoke pbalign with --bam option and then use samtools to translate from .sam to .bam .

**Comment by peterdfields** [comment]
No need for sam format just noticed the latest release of blasr broke the example code.

**Comment by peterdfields** [comment]
Does the --bam solution work when the --forQuiver flag is used?

**Comment by ylipacbio** [comment]
When input reads are in PacBio *.bam file, you do _not_  need the --forQuvier flag. Here is an example:

```
pbalign subreads.bam reference.fasta aligned.bam
```

The output aligned.bam should automatically contain all QVs needed for the new variant caller: Arrow (which replaced Quiver).

**Comment by ylipacbio** [comment]
Added a [wiki page] (https://github.com/PacificBiosciences/pbalign/wiki/Work-with-sequel-BAM-files-and-datasets.) describing how to work with PacBio Sequel data such as BAM and datasets andThe  --forQuiver option should __NOT__ be turned on when processing sequel data.
