### ISSUE TITLE
--sam is no longer supported in blasr

### ISSUE THREAD

**Issue by tangerzhang** [PacificBiosciences/pbalign#33]
Hello,
I update the latest blasr and run pbalign again.
However, it report following error and seems that pbalign is not compatible with latest blasr.
Any way to fix that?
Thanks!
____________________________________________________________________________
[zhangxt@admin1 2_quiver]$ pbalign --tmpDir /tmp --minLength 1000 --nproc 20 input/input.1.fofn LgSX.v0.PB.fasta outcmp/out_1.cmp.h5 --forQuiver
[INFO] 2016-06-02 05:01:40,705Z [pbalign.pbalignrunner _pacbio_main_runner 128] Using pbcommand v0.3.21
[INFO] 2016-06-02 05:01:40,705Z [pbalign.pbalignrunner _pacbio_main_runner 129] completed setting up logger with <function setup_log at 0x7fccab4ea938>
[INFO] 2016-06-02 05:01:40,705Z [pbalign.pbalignrunner _pacbio_main_runner 130] log opts {'file_name': None, 'level': 20}
[INFO] 2016-06-02 05:01:40,705Z [root run 255] pbalign version: 0.2.0.173392
[INFO] 2016-06-02 05:01:40,842Z [root run 178] BlasrService: Align reads to references using blasr.
[INFO] 2016-06-02 05:01:40,843Z [root Execute 63] BlasrService: Call "blasr /public4/zhangxt/project/1_LgSXasm/2_quiver/input/input.1.fofn /public4/zhangxt/project/1_LgSXasm/2_quiver/LgSX.v0.PB.fasta --out /tmp/tmpnaLwL3/WgvWHL.sam  --sam  --bestn 10 --minMatch 12  --nproc 20  --minSubreadLength 1000 --minAlnLength 1000  --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest  --randomSeed 1 "
BlasrService returned a non-zero exit status. [INFO] 2016-06-02T13:01:41 [blasr] started.
ERROR: --sam is no longer supported, use --bam, then translate from .bam to .sam
[ERROR] 2016-06-02 05:01:41,088Z [root Execute 67] BlasrService returned a non-zero exit status. [INFO] 2016-06-02T13:01:41 [blasr] started.
ERROR: --sam is no longer supported, use --bam, then translate from .bam to .sam
[INFO] 2016-06-02 05:01:41,089Z [pbalign.pbalignrunner _pacbio_main_runner 152] exiting with return code 1 in 0.38 sec.
____________________________________________________________________________

**Comment by vrainish-pacbio** [comment]
Hi,

Indeed , starting from version 5.2 blasr no longer supports --sam option.
Let me check pbalign and adjust it, if necessary

**Comment by ylipacbio** [comment]
The wiki page below describes the current workflow that we recommend to process RS II data.

https://github.com/PacificBiosciences/pbalign/wiki/Mapping-RS-II-reads-(in-movie.bax.h5)-and-calling-consensus-using-pbalign-BLASR-while--sam-option-is-deprecated

**Comment by tangerzhang** [comment]
Great!
Thanks to all of you!
I will try the new workflow.
