### ISSUE TITLE
ERROR, could not read pulse metrics for SMRTSequence

### ISSUE THREAD

**Issue by guleiathms** [PacificBiosciences/pbalign#34]
Not sure I reopened this issue.

I met this error when I run the smrtanalysis_2.3.0.140936 with patch 5 for 28 movies (28 ...p0.1.bax.h5, p0.2.bax.h5, p0.3.bax.h5), and got
```
2016-06-05 01:19:23,470 [ERROR] BlasrService returned a non-zero exit status. [INFO] 2016-06-04T16:09:37 [blasr] started.
ERROR, could not read pulse metrics for SMRTSequence m140929_122654_42139_c100719602550000001823155305141594_s1_p0/92444
```
in the align.log.

Then I run the same pipeline for that potential problematic moive (m140929_122654_42139_c100719602550000001823155305141594_s1_p0), but no error reported, with exit code 0:
```
Task 1 completed at Fri Jun 3 20:51:02 EDT 2016
Alignment Complete
Task 2 completed at Fri Jun 3 20:51:02 EDT 2016
[INFO] 2016-06-03T20:51:05 [loadPulses] started.
loading 199520 alignments for movie 1
loading 199520 alignments for movie 1
loading 199520 alignments for movie 1
loading 163226 alignments for movie 2
loading 163226 alignments for movie 2
loading 163226 alignments for movie 2
[INFO] 2016-06-03T21:52:34 [loadPulses] ended.
Task 3 completed at Fri Jun 3 21:52:34 EDT 2016
LoadPulses Complete
Task 4 completed at Fri Jun 3 21:52:34 EDT 2016
Finished on Sat Jun 4 01:52:34 UTC 2016
Task align with nproc 8 with exit code 0.
```

So what's going on when I run the pipeline with 28 movies together?

**Comment by ylipacbio** [comment]
The issue that guleiathms observed does seem to be related with blasr version. 

There was a bug in blasr_libcpp which caused blasr to raise this error when any (non-mandatory) QV is missing and this bug should have been fixed.

Would you please check that blasr used in two pipelines identical?

In addition, the following command helps to duplicate this error quickly:
```
blasr m140929_122654_42139_c100719602550000001823155305141594_s1_p0.fofn ref.fasta -holeNumbers 92000-100000 
```

**Comment by guleiathms** [comment]
Thanks Ylipacbio, the blasr version should be the latest in my pipeline and I used the same pipeline in my test. But anyway, this issue solved when I re-download that movie. So it looks like the previous data has some problem.

**Comment by ylipacbio** [comment]
Thanks for the feedback.
