### ISSUE TITLE
[Question] Use Pbalign to produce Quiver compatible cmp.h5 file without h5 files

### ISSUE THREAD

**Issue by RxLoutre** [PacificBiosciences/pbalign#44]
Hi !

I'm new to PacBio only assembly, and I was trying to use Quiver in order to polish my assemblies results. I read that Quiver need a cmp.h5 file, which is a kind of alignments, but I don't really understand against what. In order to create the cmp.h5 file, I read that I shoud use pbalign, with the --forQuiver option. 

So, I started to read the pbalign manual, and I came up to this : 

> The input PacBio reads can be in FASTA, Base HDF5, Pulse HDF5, Circular Consensus Sequence (CCS) HDF5 or file or file names (FOFN). The supported input file extensions are as follows.
FASTA : .fa or .fasta 
PacBio BASE HDF5 : .bas.h5 or .bax.h5 
PacBio PULSE HDF5 : .pls.h5 or .plx.h5 
PacBio CCS HDF5 : .ccs.h5 
File of file names : .fofn 

My problem is that, as I have a really huge coverage on my sequencing, it's very hard for me to download all the PacBio BASE HDF5 files. it take ages, and also take a lot of memory space (almost 1T of data). 

My questions are : 
- Is it necessary to use  PacBio BASE HDF5 files for pbalign ? Or can I just use my FASTA : .fa or .fasta that correspond to my filtered_subreads ?
- Can someone explain me in simple words, what this cmp.h5 file correspond to (an alignement of what against what ?)

Thanks for your concern !

Cheers,

Roxane

**Comment by rhallPB** [comment]
You don't need to use bas.h5 files for pbalign, but you do if you want to run quiver after, the bas.h5 contains more data than fastq (detailed quality values).
cmp.h5 is simply an alignment format, the input to pbalilgn is the bas.h5 (reads) and a reference, the reads are aligned to the reference and the result is stored in the cmp.h5 (similar to a bam file, but with the pacbio specific data needed for quiver).

**Comment by RxLoutre** [comment]
So, as I understand, we don't absolutely need bas.h5 files to use pbalign, but if we want to use Quiver, we should use theses files in pbalign, that's right ?
What is a reference to do such a thing ? When using Quiver, I should use as a reference the assembly, and then a list file (fofn) that contains the path where my bas.h5 files are contained, that's it ?

**Comment by RxLoutre** [comment]
Also, in the tutorial, I saw that we have to give the path of 3 bax.h5 files. But what if we have several runs ? Can we just add their paths in the fofn file ?

**Comment by rhallPB** [comment]
That's correct, the reference is the assembly, and the bax.h5 (three for each run) can be input as a fofn.
