### ISSUE TITLE
createChemistryHeader: error: too few arguments

### ISSUE THREAD

**Issue by Estel-Kitsune** [PacificBiosciences/pbalign#50]
Hi,

I have a BAM file, created using Blasr. I wanted to run Quiver on my file, but got an error message. According to [this issue report](https://github.com/PacificBiosciences/pbcore/issues/13) , it could be because the @RG line in the BAM is incomplete. Here's my @RG line:

> @RG   ID:82a1662f PU:../reads/filtered_subreads.fastq PL:PACBIO   DS:READTYPE=SUBREAD;BINDINGKIT=;SEQUENCINGKIT=;BASECALLERVERSION=

Following the advice from this report, I wanted to use createChemistryHeader.py on my BAM file. Here's my command-line:

`createChemistryHeader.py --bas_files bas.fofn sort.blasr.falcon1_p-only.bam header.p-only.txt`

However, here I'm getting another error message:

```
usage: getChemistryHeader.py [-h] [--debug] --bas_files BAS_FILES
                             [BAS_FILES ...]
                             input_alignment_file output_header_file
getChemistryHeader.py: error: too few arguments
```

I don't see what is missing in my command. The bas.fofn file contains the path to several bas.h5 files. Could you help me with this (and maybe change the usage message, as the script is not getChemistryHeader.py)?

Thanks,
Estelle

**Comment by lijingjing1** [comment]
Hi Estel-Kitsune,have you solve this problem?
I want to know what is your input file of reads fastq/fasta/bax.h5?

**Comment by Estel-Kitsune** [comment]
Hi lijingjing,

I did not solve this problem, but I found the information I was looking for (kit references) in the XML file corresponding to the bax files.

The input file of reads I used for blasr was fasta. But I ended up using bax.h5 files in order to get all the parameters required by quiver.

The input file of reads I used for "createChemistryHeader.py" was a fofn containing the paths to several bas.h5 files.

Thanks,
/E

**Comment by ylipacbio** [comment]
If you are using **SMRTAnalysis v2.3 (or previous version)** to process RSII data, you just need to call the following command in order to create inputs (cmp.h5 files) for `quiver`. You don't have to call `createChemistryHeader.py`.

```
pbalign -vv bax.h5 ref.fasta out.cmp.h5 --forQuiver
```
