### ISSUE TITLE
LoadPulses error

### ISSUE THREAD

**Issue by pawelosipowski** [PacificBiosciences/pbalign#51]
Hi, can you explain me what is happening here. It doesn't seem a big issue..
```
[ERROR] 2016-10-04 07:25:07,080Z [root Execute 67] LoadPulsesService returned a non-zero exit status. [INFO] 2016-10-04T09:23:12 [loadPulses] started.
Either the number of elements exceeds maxElement (2147483647). Or the estimated memory 
consumption exceeds maxMemory (4 GB).
Loading pulses from ./m160721_030657_42158_c100999392550000001823227209081697_s1_p0.3.bax.h5 by read.
loading 171947 alignments for movie 1
ERROR, the query sequence does not match the aligned query sequence.
HoleNumber: 157106, MovieName: m160721_030657_42158_c100999392550000001823227209081697_s1_p0, ReadIndex: 48118, qStart: 7, qEnd: 12951
Aligned sequence:<long seq here>
Original sequence:<long seq here>
loadPulses: LoadPulses.cpp:2300: int main(int, char**): Assertion `0' failed.
Aborted (core dumped)
[INFO] 2016-10-04 07:25:07,271Z [pbalign.pbalignrunner _pacbio_main_runner 153] exiting with return code 1 in 49971.90 sec.
(END)
```

**Comment by rhallPB** [comment]
What is your workflow, what versions of software are you using? The easiest fix may be to simply remove the problem read from the analysis.

**Comment by pawelosipowski** [comment]
the command is:
`pbalign /storage3/reads_b10/pacbio_2016/pb_2016.fofn /storage3/long_read_assembly/polishing/pb_B10v2_12000.fasta /storage3/long_read_assembly/polishing/pbalign_out.cmp.h5 --forQuiver --log-file pbalign.log --nproc 24`
pbalign 3.0
blasr   5.3.90d98ad
does quiver file is valid even though all the process wasn't finished?

**Comment by pawelosipowski** [comment]
Anyone?

**Comment by ylipacbio** [comment]
Blasr 5.0+ no longer generates SAM output which is compatible with samtoh5/loadPulses. The `pbalign bax.h5 ref.fasta out.cmp.h5` has been deprecated.

It's recommended to convert any bax.h5 files to bam first and then call `pbalign bam ref.fasta out.bam` to make alignments for further quiver polishing. See [wiki](https://github.com/PacificBiosciences/pbalign/wiki/Mapping-RS-II-reads-(in-movie.bax.h5)-and-calling-consensus-using-pbalign-BLASR-while--sam-option-is-deprecated) for details.

It seems like you still want to generate alignments in cmp.h5 files, then you have to go back to earlier versions of blasr/pbalign, which was discussed in [this pitchfork issue](https://github.com/PacificBiosciences/pitchfork/issues/305)

I am closing this issue.
