### ISSUE TITLE
Help Needed with Pbalign SamFilter

### ISSUE THREAD

**Issue by anniiee9** [PacificBiosciences/pbalign#62]
Hi all. I have been trying to run Pbalign with bax.h5 files from my PacBio data. I am facing this problem:

2016-12-04 08:45:37,051 [INFO] FilterService: Filter alignments using samFilter. 2016-12-04 08:45:37,067 [ERROR] FilterService returned a non-zero exit status. /bin/sh: 1: samFilter: not found

However, samFilter is available in my system and accessible to all.

Can anybody please suggest how to over ride this problem? I need the solution urgently.

**Comment by mhsieh** [comment]
which build exactly did you run? e.g. did you build your own pbalign, or is it from a software installation?

**Comment by ylipacbio** [comment]
Close inactive issues.
