### ISSUE TITLE
pbalign no longer supports CMP.H5 Output in 3.0

### ISSUE THREAD

**Issue by RxLoutre** [PacificBiosciences/pbalign#67]
Hi !

I finally managed to install pitchfork (I saw this post : https://github.com/PacificBiosciences/pitchfork/issues/292 and it helped me ).

Now, I've started to run pbalign within pitchfork, with the following command : 

```
pbalign --forQuiver /media/loutre/SUZUKII/assembly_tries/polishing/raw_reads.fofn /media/loutre/SUZUKII/assembly_tries/pb_268_p_ctg.fasta /media/loutre/SUZUKII/assembly_tries/polishing/falcon_suzukii.cmp.h5
```
And I got this error : 

```
[WARNING] 2017-01-10 13:16:59,012Z [root _makeSane 147] Option --forQuiver has been deprecated in 3.0
pbalign no longer supports CMP.H5 Output in 3.0.
IOError: pbalign no longer supports CMP.H5 Output in 3.0.
[INFO] 2017-01-10 13:16:59,014Z [pbalign.pbalignrunner _pacbio_main_runner 153] exiting with return code 1 in 1.19 sec.
```

However, on the pbalign documentation, ( https://github.com/PacificBiosciences/pbalign/blob/master/doc/howto.rst I'm referring to this one), the same command construction is used.

I need to use pbalign to produce a .cmp.h5 file in order to use quiver to polish my assembly. In the quiver documentation (https://github.com/PacificBiosciences/GenomicConsensus ) it says we can use a .cmp.h5 file. 

I'm kind of lost of what procedure I should use to polish my assembly using my raw reads, now that pbalign does not output a .cmp.h5 file.

Can someone help me with this ?

Cheers,

Roxane

**Comment by ylipacbio** [comment]
https://github.com/PacificBiosciences/pbalign/wiki
pbalign no longer supports BAS.H5->CMP.H5 files, please convert your BAX|BAS.H5 files to BAM.

If for some reason you still want to use H5 files, please install legacy_pbalign.
```
git clone git@github.com:PacificBiosciences/pitchfork.git
git checkout legacy_pbalign
cd pitchfork
make init
make pbalign PREFIX=/opt/mybuild             # if you want to build legacy_pbalign
bash --init-file /opt/mybuild/setup-env.sh # either to use the build in the sub-shell
source /opt/mybuild/setup-env.sh           # or     to use the build in current shell 
```

**Comment by migrau** [comment]
ylipacbio, sorry I am a bit confused.  I have *.bax.h5 files that I want to use with quiver and an assembly. With the latest pitchfork installed, should I convert the files to bam, with bax2bam and then use these bam files with pbalign? But you recommend to use "--forQuiver" only with BAX.H5 (https://github.com/PacificBiosciences/pbalign/wiki/Work-with-sequel-BAM-files-and-datasets.) What shoud I do? The only solution is to use the legacy_pbalign?
Thanks,

**Comment by RxLoutre** [comment]
Hello migrau,

I had the same problem as you of incompatibility using pitchfork tools.
If you want to use functional PacBio tools with bax/bas files, I recommend to you to do this : 
-download & install SMRT Portal 2.3 (I'm not sure about the version I can check)
-when it is installed, go to /opt/smrtanalysis/current/etc/ (if you have installed everything as specified by Pacific Biosciences)
- you can source a file named setup.sh, that will set up an environment where you can use all PacBio tools 

I couldn't find any other method to work with h5 files, I think that PacBio are deeply renewing their pipeline, changing all h5 file to classic bam/sam or fasta file.

So you can try my method, I can help you with the installation of SMRT Portal if you need !

Tell me if you are trying it and if it succeed !

Cheers,

Roxane

**Comment by migrau** [comment]
I appreciate your help, RxLoutre. I am working on a cluster and I just want to use quiver so I would like to avoid the installation of the complete SMRTPortal 2.3 software. I have tried with pitchfork tools but, as you said, it looks confusing with the new incompatibilities. I will ask to pitchfork staff but if not I will try installing SMRT Portal.
Thanks!

**Comment by RxLoutre** [comment]
I was just on the same pain, I just wanted to use quiver, and after 1 month trying to ask pitchfork people, waiting for answers that didn't helped me, trying to install myself... It was really a nightmare, and I make it only by installing SMRT Portal.

You know, if it's the installation that scared you, I was thinking the same so I understand, but SMRT Portal is really EASY to install. There is no particular configuration, you need Tomcat and MySQL, which you may have if you work on a cluster, and then installer do all the painful stuff for you. And then, you even don't have to create an account or something, just go on this particular directory and use pacbio tools, such as pbalign (step necessary before polishing) and quiver.

I hope you will make it !

Cheers,

Roxane

**Comment by mhsieh** [comment]
Pitchfork is an unofficial path of building program from our open source project, it's certainly very painful to build because that's the hard way. And it's not supported.

If your requirement can be satisfied by using smrtanalysis-2.3, please use that instead.

**Comment by ylipacbio** [comment]
@migrau  

- (1) Please always convert RSII   bax.h5 files to BAM files to use the latest PacBio tool 
- (2) pbalign automatically carries all the QV values from input bam files to output aligned bam files, and thus the output alignments can be directly feed into `variantCaller --algorithm=best` to make consensus calls. `variantCaller --algorithm=best` will automatically use `Quiver` when input is bam file converted from RSII bax.h5 data, and will use `Aarow` when input is sequel data.
- (3) pbalign `--forQuiver` option has been deprecated post SMRTAnalysis v 2.3, and should have NO impact on outputs, i.e., `pbalign in.bam ref.fa out.bam` and `pbalign in.bam ref.fa out.bam --forQuiver` should produce identical results.
- (4) if you just want to call consensus of RSII data (e.g., polishing assembly), first convert bax.h5 to bam, then call pbalign taking bam as input (e.g., `pbalign in.bam ref.fa aligned.bam`), then call `variantCaller --algorithm=best aligned.bam --referenceFilename ref.fa -o output.fasta -o output.fastq`

**Comment by migrau** [comment]
Thanks, @RxLoutre. Finally, I did it with SMRT 2.3 and now I'm trying it with SMRT 3.0+, in order to compare results.

@ylipacbio. So if I have several [1-3].bax.h5 files, after convert them to bam (using bax2bam) can I merge them in a single bam file with bamtools and then run pbalign & variantCaller? 
Thank for your help,

**Comment by ylipacbio** [comment]
That's correct. 1, call pbalign for each bam file, 2, merge output aligned bam files to a single file, 3, call variantCaller.

**Comment by ptranvan** [comment]
For baxtobam, do you recommend 

1) classic conversion 

> bax2bam movie.1.bax.h5 movie.2.bax.h5 movie.3.bax.h5 -o movie --subread

or

2) propagate additional pulse features (QVs).

as described here:

https://github.com/PacificBiosciences/blasr/wiki/bax2bam-wiki:-installation,-basic-usage-and-FAQ

**Comment by ylipacbio** [comment]
Classic conversion is good for most use cases.
Including all QVs if you want to look into base modifications.

**Comment by ptranvan** [comment]
@ylipacbio 

Is it not `variantCaller --algorithm=quiver ...` instead of `variantCaller --algorithm=best` ?
