### ISSUE TITLE
temporary files not moved properly to output file

### ISSUE THREAD

**Issue by eldariont** [PacificBiosciences/pbalign#71]
Hi,

I'm experiencing a problem when using pbalign's --tmpDir option. pbalign correctly outputs the alignment into the given temporary directory but then fails to move the final result to the given output location. **The final result is just a link to the (now deleted) temporary directory.**

This is my command:
`pbalign reads.bam hg19.fa aln.sam --profile --nproc 20 --tmpDir mytmp/ --unaligned unaln.txt --debug`

Standard output:
```
[INFO] 2017-03-08 16:14:17,510Z [root Execute 63] FilterService: Call "rm -f /mytmp/tmpxESsBr/hjWhOc.sam && ln -s mytmp/tmpxESsBr/gCyd6I.sam mytmp/tmpxESsBr/hjWhOc.sam"
[INFO] 2017-03-08 16:14:23,802Z [root _output 188] OutputService: Genearte the output SAM file.
[DEBUG] 2017-03-08 16:14:23,802Z [root _output 189] OutputService: Move mytmp/tmpxESsBr/hjWhOc.sam as aln.sam
[DEBUG] 2017-03-08 16:14:23,996Z [root _cleanUp 218] Clean up temporary files and directories.
[DEBUG] 2017-03-08 16:14:24,568Z [root CleanUp 205] Remove a temporary file mytmp/tmpxESsBr/gCyd6I.sam
[DEBUG] 2017-03-08 16:14:36,862Z [root CleanUp 212] Remove a temporary dir mytmp/tmpxESsBr
```
Apparently, blasr outputs `mytmp/tmpxESsBr/gCyd6I.sam`. The filter service just creates a symbolic link `mytmp/tmpxESsBr/hjWhOc.sam` pointing to this file. Then this symbolic link is moved to aln.sam and the original temporary files are deleted which leaves the symbolic link aln.sam pointing to a deleted file.

As I understand it, the important command is line 191 in  pbalign/pbalign/pbalignrunner.py:
`shutil.move(real_ppath(inSam), real_ppath(outFile))`. In my python version (2.7.9), this moves the symbolic link but not the file it points to.

Cheers
David

pbalign version 0.3.0, blasr version 5.3.5b30da0, Python 2.7.9

**Comment by ylipacbio** [comment]
Please do not run pbalign with --tmpDir in tmpDir, e.g., 

```cd /abc && pbalign reads ref out.sam  --tmpDir xyz ``` should work fine
```cd /abc && pbalign reads ref out.sam  --tmpDir /abc ``` should fail

**Comment by Zhenhuiz** [comment]
Hi eldariont,

I also got the same problem. But I found if the output is bam then I can get the output file.

**Comment by eldariont** [comment]
@ylipacbio I do not run pbalign from the tmpDir but it still fails to exit with the output file at the proper place.

@Zhenhuiz Yes, bam output files are apparently post-processed with the bampostservice and not moved with shutil.move (see line 185 in `pbalign/pbalign/pbalignrunner.py`).

So what would be a good solution? Replacing shutil.move with shutil.copy as this copies the file and not the link?!

**Comment by ylipacbio** [comment]
When option `--keepTmpFiles` is turned on, pbalign will keep all the intermediate files. 
Would you please try:
`pbalign read.fasta lambdaNEB.fa out.sam --keepTmpFiles`

**Comment by benoistlaurent** [comment]
Hi,

Same problem here.

It is quite clear to me that:

1. pbalign makes symbolic links
2. it uses `shutil.move` which moves the symbolic link instead of copying the file
3. remove the temporary directory.

Hence,

- using default options, the original output file has been removed
- same behavior using a custom temporary directory (which is expected)
- it works fine using the `--keepTmpFiles` option, as the temporary directory is not removed anymore.

Clearly it is a major bug, as the program default behavior is to remove the output file it just created.

Cheers,
Ben

**Comment by ylipacbio** [comment]
Have filed a bug reporting this issue and will keep you posted when this bug is fixed.

**Comment by mhsieh** [comment]
fixed - https://github.com/PacificBiosciences/pbalign/commit/28b46e887eedc934dc67cd3b4f02b31a004576c1
Apology for the delay ... we will start to look at the refactoring effort.
