### ISSUE TITLE
util/progutil.py could use a slight improvement

### ISSUE THREAD

**Issue by flowers9** [PacificBiosciences/pbalign#73]
Because one of the various third party parts of PacBioSmrtLink includes libtinfo.so, which is linked to by bash, I've seen a bunch of non-fatal error messages when running stuff through the various pipelines.  This is mostly harmless, but pbalign fails out because it can't get the version of samtools and ends up calling it incorrectly.  The simple fix is:

```
--- progutil.py    2017-01-10 13:03:39.000000000 -0600
+++ progutil.py 2017-03-30 14:12:47.715859197 -0500
@@ -61,7 +61,7 @@
         errMsg : the error message
     """
     logging.info(name + ": Call \"{0}\"".format(cmd))
-    output, errCode, errMsg = backticks(cmd)
+    output, errCode, errMsg = backticks(cmd, merge_stderr=False)
     if errCode != 0:
         errMsg = name + " returned a non-zero exit status. " + errMsg
         logging.error(errMsg)
```

which prevents stderr from messing around with stdout.

**Comment by ylipacbio** [comment]
Thanks for reporting this, it has been taken care of by MJ. Will show up in the next commit.

**Comment by mhsieh** [comment]
Dave:
    The suggestion will be in place for the next repo update. If your organization have a smrtlink installed with this kind of tinfo problems, you can move ncurses library out of the way, this will help avoid the spurious stderr message.
