### ISSUE TITLE
samtoh5 returned a non-zero exit status

### ISSUE THREAD

**Issue by flashton2003** [PacificBiosciences/pbalign#9]
Hello!

I'm running pbalign installed from the github repository (the 0087df7 commit of blasr, copy of pbalign pulled down today, can't find the commit number). My command line is

pbalign --nproc 4 --forQuiver nctc129.fofn nctc129_genome.fasta nctc129.cmp.h5

Unfortunately, pbalign crashes with the following error

2015-06-02 16:12:39,870 [ERROR] samtoh5 returned a non-zero exit status.[INFO] 2015-06-02T16:12:35 [samtoh5] started.
HDF5-DIAG: Error detected in HDF5 (1.8.15) thread 0:
  #000: H5Pdcpl.c line 881 in H5Pset_chunk(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: H5Pint.c line 3381 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: H5Pint.c line 3331 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
terminate called after throwing an instance of 'H5::PropListIException'
Aborted (core dumped)

It looks like a problem with my HDF5 installation, but I'm struggling to debug. Do you have any pointers?

Many thanks,

Phil

**Comment by ylipacbio** [comment]
We have encountered similar problem when compiling blasr on one platform (or using a gcc version) and linking to hdf5 lib compiled on another platform (using a difference gcc version). You may want to double check whether blasr and hdf5 were compiled on the same platform (or using the same gcc). 

In addition, if you have multiple hdf5 library installed to your environment PATH, make sure blasr is linking to the right one.
